### PR TITLE
Added proposed future chapters.

### PR DESCRIPTION
**Pull request by jonthegeek**
Based on https://github.com/tidymodels/TMwR/pull/130

### CODE REVIEW

**Review by MayaGans — APPROVED** [review]
LGTM!!

**Comment by jonthegeek** [comment]
Hmm. I think requesting from both of you broke it, maybe? It wont' let me merge even though you approved. I'm going to re-request review, @MayaGans .

**Comment by tanho63** [comment]
@jonthegeek Maya didn't have write access to the repo - she's a `member` and not `owner` of the r4ds org - so her approval wasn't processed til I just added her manually to the repo

**Comment by jonthegeek** [comment]
> @jonthegeek Maya didn't have write access to the repo - she's a `member` and not `owner` of the r4ds org - so her approval wasn't processed til I just added her manually to the repo

Aha! She's an owner now!

**Pull request merged**
