### PR TITLE
Add embedded videos to bookdown

### PR DESCRIPTION
**Pull request by tanho63**
Add embedded video link

### CODE REVIEW

**Comment by tanho63** [comment]
(Should I go back and add the others? @jonthegeek )

**Comment by jonthegeek** [comment]
> (Should I go back and add the others? @jonthegeek )

Sure!

**Review by jonthegeek — CHANGES_REQUESTED** [review]
Add the other videos, too. I think a section "Meeting Videos" after the last section should be the standard (so probably for Chapter 4, too).

**Review by jonthegeek — APPROVED** [review]
Oops, I forgot this was still waiting for me!

**Pull request merged**
