### PR TITLE
Create pr_check.yml

### PR DESCRIPTION
**Pull request by tanho63**

### CODE REVIEW

**Comment by tanho63** [comment]
This PR creates a GHA that automatically checks if the book will build based on the PR

**Comment by jonthegeek** [comment]
Neat! Letting the check finish before approving...

**Comment by tanho63** [comment]
This definitely needs squash merged if I'm gonna be doing it as "try til it stops failing"!

**Review by jonthegeek — APPROVED** [review]
Sweet, it looks like it worked!

**Pull request merged**
